version: '3.3'

services:
  db:
    image: postgres:9.5
    container_name: evs_postgres
    volumes:
      - "${HOME}/docker/volumes/postgres:/var/lib/postgresql/data"
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_DB: "evs"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "docker"


  db_api:
    depends_on:
      - db
      - web_api
    build: apis/db
    image: evs-db-api:latest
    container_name: evs_db_api
    ports:
      - "${DB_API_PORT}:8080"
    environment:
      DB_HOST: "db"
      DB_PORT: "5432"
      WEB_API_HOST: "web_api"
      WEB_API_PORT: "8080"

  telemsg_api:
    build: apis/telemsg
    image: evs-telemsg-api:latest
    container_name: evs_telemsg_api
    ports:
      - "${TELEMSG_API_PORT}:8080"
    environment:
      TELEGRAM_TOKEN: "${TELEGRAM_TOKEN}"
      TELEGRAM_ADMIN_ID: "${TELEGRAM_ADMIN_ID}"

  web_api:
    build: apis/web
    image: evs-web-api:latest
    container_name: evs_web_api
    ports:
      - "${WEB_API_PORT}:8080"

  telebot:
    depends_on:
      - db_api
      - telemsg_api
      - web_api
    build: hosts/telebot
    image: evs-telebot:latest
    container_name: evs_telebot
    environment:
      TELEGRAM_TOKEN: "${TELEGRAM_TOKEN}"
      DB_API_HOST: "db_api"
      DB_API_PORT: 8080
      TELEMSG_API_HOST: "telemsg_api"
      TELEMSG_API_PORT: 8080
      WEB_API_HOST: "web_api"
      WEB_API_PORT: 8080
