services:
  db:
    image: postgres:9.5
    volumes:
      - "${HOME}/docker/volumes/postgres:/var/lib/postgresql/data"
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    restart: "on-failure"

  db_api:
    depends_on:
      - db
      - web_api
    build: apis/db
    image: evs-db-api:latest
    ports:
      - "${DB_API_PORT}:8080"
    environment:
      DB_HOST: "db"
      DB_PORT: "5432"
      WEB_API_HOST: "web_api"
      WEB_API_PORT: "8080"
    restart: "on-failure"

  telemsg_api:
    build: apis/telemsg
    image: evs-telemsg-api:latest
    ports:
      - "${TELEMSG_API_PORT}:8080"
    environment:
      TELEGRAM_TOKEN: "${TELEGRAM_TOKEN}"
      TELEGRAM_ADMIN_ID: "${TELEGRAM_ADMIN_ID}"
    restart: "on-failure"

  web_api:
    build: apis/web
    image: evs-web-api:latest
    ports:
      - "${WEB_API_PORT}:8080"
    restart: "on-failure"

  frontend_api:
    depends_on:
      - db_api
      - web_api
    build: apis/front
    image: evs-front-api:latest
    environment:
      DB_API_HOST: "db_api"
      DB_API_PORT: "8080"
      WEB_API_HOST: "web_api"
      WEB_API_PORT: "8080"
    restart: "on-failure"

  nginx:
    depends_on:
      - frontend_api
    image: nginx:1.23
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./hosts/nginx/nginx.conf/:/etc/nginx/conf.d/nginx.conf:ro
      - certbot-www:/var/www/certbot/:ro
      - certbot-conf:/etc/nginx/ssl/:ro

  certbot:
    depends_on:
      - nginx
    image: certbot/certbot:v1.28.0
    volumes:
      - certbot-www:/var/www/certbot/
      - certbot-conf:/etc/letsencrypt/

  telebot:
    depends_on:
      - db_api
      - telemsg_api
      - web_api
    build: hosts/telebot
    image: evs-telebot:latest
    environment:
      TELEGRAM_TOKEN: "${TELEGRAM_TOKEN}"
      TELEGRAM_ADMIN_ID: "${TELEGRAM_ADMIN_ID}"
      DB_API_HOST: "db_api"
      DB_API_PORT: 8080
      TELEMSG_API_HOST: "telemsg_api"
      TELEMSG_API_PORT: 8080
      WEB_API_HOST: "web_api"
      WEB_API_PORT: 8080
    restart: "on-failure"

  grafana:
    depends_on:
      - db
    image: grafana/grafana:9.0.2
    volumes:
      - ./hosts/grafana/data:/var/lib/grafana
    ports:
      - "3000:3000"

volumes:
  certbot-www:
  certbot-conf:
